# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    providers:
#        in_memory:
#            memory: ~
        app_provider_db:
                    entity:
                        class: AppBundle:User
                        property: username
                        # if you're using multiple entity managers
                        # manager_name: customer

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)
            security: false

        backend:
            pattern: ^/
            anonymous: ~
            http-basic: ~
            form_login:
                login_path: /login
                check_path: /login_check
                csrf_provider: security.csrf.token_manager
            logout:
                path:   /logout
                target: /
            provider: app_provider_db

        default:
            anonymous: ~

    access_control:
        - { path: ^/(customer|provider)/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/customer, role: ROLE_CUSTOMER }
        - { path: ^/provider, role: ROLE_PROVIDER }
        - { path: ^/employee, role: ROLE_EMPLOYEE }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/admin/, role: ROLE_ADMIN }